### ISSUE TITLE
Everying work fine on 10.14, but can't boot 10.15 installer.

### ISSUE THREAD

**Issue by Void-JackLee** [dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580#1]
I tried your EFI, it was super completely fine, so I attempt to upgrade the system to 10.15, but it stop at booting, before the USB working. My computer was really similar to yours: ASUS Prime Z390-A, i9-9900K with UHD630, AMD Radeon VII. Here is the image.
![All](https://user-images.githubusercontent.com/25055771/64429629-fa30c100-d0e8-11e9-86f2-4e9f733540b1.jpg)
![Detail](https://user-images.githubusercontent.com/25055771/64429688-22202480-d0e9-11e9-9e7c-d6eaabb19c0f.jpg)
I suspect the problem was ```AppleNVME Assert failed: (0 != data) ReleaseIDNode file: .......```, but I'm not sure. By the way, your EFI was perfect on 10.14.

**Comment by dhckdgjs** [comment]
Thanks for your feedback. But I had not upgrade to 10.15 yet. I usually don’t use beta OS. Unfortunately I can’t figure out to solve that problem now.
After 10.15(not beta), I’ll consider your idea about that issue.

**Comment by Void-JackLee** [comment]
I found solution on a forum(pcbeta.com), it said that it was a common problem with ASUS motherboard when upgrade 10.15 beta 5 and later version. Also,it provide a method which is using SSDT-LPC.aml to fix losing EC device, but the forum was closed until October, so i just need wait.

**Comment by Void-JackLee** [comment]
I succeed!!!!!!!!! I saw the cache of the forum, then I Googled the method of adding ```Device(EC)``` to SSDT, I tried, and no more panic. But I got a new problem, no video output, so I add a new kext which can search on GitHub, named ```Whatevergreen```, it works, and now entered to the desktop.
![Suceed!!!!!!!!](https://user-images.githubusercontent.com/25055771/64907835-61262980-d72a-11e9-931a-90e1e1c4548d.jpg)

**Comment by Void-JackLee** [comment]
I will fork your project, and add support to 10.15, hope it can be used when the formal version released. Plus, I add the UHD630 iGPU support to the clover config.
<img width="751" alt="iGPU" src="https://user-images.githubusercontent.com/25055771/64907906-6cc62000-d72b-11e9-85f2-8a9de1d63d7c.png">
But it still has some strange display on setting, I am still figuring out.
<img width="751" alt="bugs" src="https://user-images.githubusercontent.com/25055771/64907918-94b58380-d72b-11e9-8025-b7e916d4c393.png">

**Comment by dhckdgjs** [comment]
> I succeed!!!!!!!!! I saw the cache of the forum, then I Googled the method of adding `Device(EC)` to SSDT, I tried, and no more panic. But I got a new problem, no video output, so I add a new kext which can search on GitHub, named `Whatevergreen`, it works, and now entered to the desktop.
> ![Suceed!!!!!!!!](https://user-images.githubusercontent.com/25055771/64907835-61262980-d72a-11e9-931a-90e1e1c4548d.jpg)


===

First of all, thank you for your support :)
I'll consider your method(add EC device to SSDT) in Catalina.


By the way, I need something to tell your settings.

1. Whatevergreen.kext(a.k.a WEG)

This kext makes FCPX export speed too slow. Basically, WEG is very useful in nearly all other settings. But it(we call headless settings) can't use H/W acceleration 100%(like Intel Quicksync). So I didn't use WEG in my previous setting.

I recommend you compare FCPX export speed with/without WEG.
BUT if you update major or supplemental update already, normally it causes BLACKOUT issue. If you had backup your EFI before the update, it helps your Blackout(Black screen) issue. Just restore your old EFI and boot once, then restore your latest EFI again. After that, the blackout issue will disappear. I don't know what makes solve this issue. But it works in many blackout issues related update.

In your situation, just change your current EFI to old EFI(without WEG.kext) then boot once after that, restore to previous EFI(without WEG.kext but with your EC-SSDT).



2. Add iGPU name on the PCI list

I use the Intel Power Gadget and iStat when I test my settings. If I change iGPU name 'Intel HD Graphics CFL' to 'UHD Graphics 630(or anything)' the Intel Power gadget can't recognize iGPU properly. I need to check core frequency and usage of dram for full H/W acceleration of iGPU.(100% accelerate not just 'Headless')

But if you don't need check status of iGPU, it doesn't matter. That is just only cosmetic.

**Comment by Void-JackLee** [comment]
> ===
First of all, thank you for your support :)
I'll consider your method(add EC device to SSDT) in Catalina.
By the way, I need something to tell your settings.
Whatevergreen.kext(a.k.a WEG)
This kext makes FCPX export speed too slow. Basically, WEG is very useful in nearly all other settings. But it(we call headless settings) can't use H/W acceleration 100%(like Intel Quicksync). So I didn't use WEG in my previous setting.
I recommend you compare FCPX export speed with/without WEG.
BUT if you update major or supplemental update already, normally it causes BLACKOUT issue. If you had backup your EFI before the update, it helps your Blackout(Black screen) issue. Just restore your old EFI and boot once, then restore your latest EFI again. After that, the blackout issue will disappear. I don't know what makes solve this issue. But it works in many blackout issues related update.
In your situation, just change your current EFI to old EFI(without WEG.kext) then boot once after that, restore to previous EFI(without WEG.kext but with your EC-SSDT).
Add iGPU name on the PCI list
I use the Intel Power Gadget and iStat when I test my settings. If I change iGPU name 'Intel HD Graphics CFL' to 'UHD Graphics 630(or anything)' the Intel Power gadget can't recognize iGPU properly. I need to check core frequency and usage of dram for full H/W acceleration of iGPU.(100% accelerate not just 'Headless')
But if you don't need check status of iGPU, it doesn't matter. That is just only cosmetic.

Thanks for your suggestion, I will try without WEG. Before I add it, the ```UHD Graphics 630(or anything)``` was ```Intel HD Graphics CFL```, I didn't change any name. I am not using FCPX to test the influence of WEG, when I have some project to make, I will test it.

**Comment by Void-JackLee** [comment]
> BUT if you update major or supplemental update already, normally it causes BLACKOUT issue. If you had backup your EFI before the update, it helps your Blackout(Black screen) issue. Just restore your old EFI and boot once, then restore your latest EFI again. After that, the blackout issue will disappear. I don't know what makes solve this issue. But it works in many blackout issues related update.

It was odd, next week I will figure out does it work on 10.15. I am at school using macbook, so I can't test it on my Hackintosh immediately.

**Comment by dhckdgjs** [comment]
FCPX most affected by Intel quicksync. But other apps(like photos, imovie etc) use the Quicksync also.

**Comment by nariox** [comment]
It seems like the Aptio fix wil no longer be maintained, instead the development will move on to OpenCore. I got OpenCore to work on my ASUS Z390-A (with a i5-9400 and a humble RX560). Will create a repo soon.

I am still getting lots of USB errors in the log, but it doesn't seem to affect anything. The only ports that don't work are the ones in the TB display (which is a bit of a nightmare), but everything else seems working. (Hackintool reports that the decoder is supported and Videoproc shows that both H264 and HEVC are hardware accelerated).

I haven't upgraded to 10.15 yet, but I might in the near future.

**Comment by nariox** [comment]
Done it, my OpenCore settings are in: https://github.com/nariox/ASUS-PRIME-Z390-A-HACKINTOSH-Clover-iGPU-with-dGPU-UHD630-RX580

If any of you could test it with Catalina, I'd be very thankful. (I've built the computer for my wife, so I can't mess with it too often).

You need to change config.plist to your Serial and SmUUID. And NVRAM doesn't seem to be working yet, I'm still looking into it (so no iMessage as far as I can tell).

**Comment by dhckdgjs** [comment]
Thank you for your effort nariox ;)
I haven not upgraded 10.15 yet too. I'll report a feedback after move on to Catalina soon!

**Comment by nariox** [comment]
Thank you all.
One thing I have found out is that NVRAM does seem to be working, but you need to list all the variables you want to load/save in the config.plist. But once I added the one I was testing with, it started saving and restoring it on boot.

**Comment by nariox** [comment]
Success! Pulled the trigger last night. It works well, side car also works (although iPad shows "not charging" from the front panel). No bugs to report yet. (Again, wife's computer, so haven't had time to test extensively, but works well enough while I was testing).

**Comment by nariox** [comment]
Word of caution, WEG needs to be updated before upgrading to 10.15.1.

I found out that for some reason some of the options in config.plist were converted to <DATA> type, instead of <STRING>. If someone could help me convert those back, that'd be great. Also, seems like sometimes USB stops working after sleep. Still looking into that, probably need to redo the USBMap.

**Comment by nariox** [comment]
I have made several updates to my repo to fix some freezes/kernel panics. I've also fixed the strings of config.plist. USB ports now work fine (disabled some in the back).

If people could test it out, I'd be very thankful. I've not had any issues since the new fixes. If enough people confirm it to be working, I can send a pull request to this repo.

**Comment by nariox** [comment]
Hello again, @dhckdgjs , I have made quite a few changes in my repo. I'm wondering if you'd be willing to merge those or you'd prefer to keep the repos separate.
Either way, thank you for this repo, it was really helpful when I was trying to figure out how to get started with my Hackintosh.

**Comment by dhckdgjs** [comment]
Hello @nariox.
I’m so flattered. Thanks ;)

I changed my settings and committed recent EFI for 10.15.3.
Still, I don't use WEG and H/W acceleration works fine in any applications.

I recommend you check first my new EFI on the commit page.
Thank you for your contributions.

**Comment by dhckdgjs** [comment]
[ASUS PRIME Z390-A EFI (All Work, Sleep well disable hdmi audio) 2020.02.zip](https://github.com/dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-Clover-iGPU-with-dGPU-UHD630-RX580/files/4230242/ASUS.PRIME.Z390-A.EFI.All.Work.Sleep.well.disable.hdmi.audio.2020.02.zip)

If you can't find new committed files, check the above links.

---

**ASUS PRIME Z390-A Clover EFI for Catalina 10.15.3**

- Everything works fine


**Issues and Solutions**

- Force reboot after Wake-up
-> Disable HDMI audio output in the Device properties

- Blackout issue only one DP(Display Port) Monitor in dual monitor circumstance
-> Change FB Name to Orinoco, Check Inject ATI, Set 1 for Dual Link

**Comment by nariox** [comment]
Great. Maybe we can keep both repos separate then. I think it's good that people can choose between clover and opencore. In case you want to switch to OpenCore, let me know, otherwise, good luck. (;
