### ISSUE TITLE
Opencore 0.6.0

### ISSUE THREAD

**Issue by magnificent3** [dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580#2]
I'm trying to do the same thing, but I'm already on opencore 0.6.0.
Have you done the upgrade?

**Comment by dhckdgjs** [comment]
I already updated OC 0.6.0(with WEG Ver.)
Please check my repo again.

**Comment by magnificent3** [comment]
Thank you so much! Gonna try this!
I’ll let you know.
My config is a bit like yours except I have an Asus Prime Z390-M.

**Comment by magnificent3** [comment]
So far so good!! Works great! Thanks for your help!
