### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by magnificent3** [dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580#3]
Hi there!!
Have you tried this config with Big Sur?
Can you share your EFI if you have done so?
Thanks Again!!!

**Comment by dhckdgjs** [comment]
Unfortunatelly I had not update newer version of Mac os because I use my gears for work.
Maybe I update Mac os 10.16.2 or 16.3.

**Comment by tof92130** [comment]
I upgraded your config to open core 0.6.4 by changing few files as explained here https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#boot-efi-handoff then I upgraded few key text and Mac OS Big Sur 11.1 is running perfectly.

**Comment by magnificent3** [comment]
> I upgraded your config to open core 0.6.4 by changing few files as explained here https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#boot-efi-handoff then I upgraded few key text and Mac OS Big Sur 11.1 is running perfectly.

Hi, can you share your EFI?

**Comment by wbews** [comment]
> I upgraded your config to open core 0.6.4 by changing few files as explained here https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#boot-efi-handoff then I upgraded few key text and Mac OS Big Sur 11.1 is running perfectly.

Hi, can you share your EFI?

**Comment by nariox** [comment]
You can check my port, no guarantees, but it is working well on Big Sur.

**Comment by luhua98989898** [comment]
> You can check my port, no guarantees, but it is working well on Big Sur.

your usb port work well？ and sleep？ on the big sur

**Comment by dhckdgjs** [comment]
> > You can check my port, no guarantees, but it is working well on Big Sur.
> 
> your usb port work well？ and sleep？ on the big sur

Use ver 1.2 EFI. Everything works well on Big sur.

**Comment by luhua98989898** [comment]
> > > You can check my port, no guarantees, but it is working well on Big Sur.
> > 
> > 
> > your usb port work well？ and sleep？ on the big sur
> 
> Use ver 1.2 EFI. Everything works well on Big sur.

where？

**Comment by dhckdgjs** [comment]
> > > > You can check my port, no guarantees, but it is working well on Big Sur.
> > > 
> > > 
> > > your usb port work well？ and sleep？ on the big sur
> > 
> > 
> > Use ver 1.2 EFI. Everything works well on Big sur.
> 
> where？

Definitely in my repo. Check the release menu.
And please read my readme.md

https://github.com/dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580/releases
