### ISSUE TITLE
v1.0 release confirmed working well

### ISSUE THREAD

**Issue by ClassicOldSong** [dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580#5]
https://github.com/dhckdgjs/ASUS-PRIME-Z390-A-HACKINTOSH-iGPU-with-dGPU-UHD630-RX580/releases/tag/1.0

Perfectly bootable. I migrated my own Clover version to this version and upgraded from Catalina to BigSur 11.2.3 without issue.

My setup is almost identical to this repo's, only added a SATA optical drive and have a 9900K instead of 8700.

I couldn't even get BigSur to boot before this configuration is released, so huge thanks to @dhckdgjs !

Made some minor changes to the configuration to add Pioneer BD09 optical drive support(don't mind if you don't have one), fixed internal USB port totally not found and instant wakeup after sleep issue by migrating my own edited SSDT-EC.aml, USBInjectAll.kext from my previous configuration, disabling USBPorts.kext, SSDT-USBW.aml and SSDT-USB-Reset.aml.

iGPU works well alongside with dGPU, sidecar not tested but should work.

iMessage, FaceTime and Handoff works when having BoardSerial configured.

Opening this issue to give a feedback and hope will help others.

**Comment by ClassicOldSong** [comment]
Update: After upgraded to BigSur 11.3, XhcPortLimit should be unchecked, otherwise some rear USB ports will be missing.

**Comment by dhckdgjs** [comment]
Check this link as below.
This quick fix for Z590, but basically same solution for Z390 also.
[Big sur 11.3 update USB issue]
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2245176

**Comment by dhckdgjs** [comment]
> Update: After upgraded to BigSur 11.3, XhcPortLimit should be unchecked, otherwise some rear USB ports will be missing.

Check this link as below.

This quick fix for Z590, but basically same solution for Z390 also.

[Big sur 11.3 update USB issue]
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2245176

**Comment by ClassicOldSong** [comment]
Unfortunately this doesn't enable USB3.0 back, but fixed issue where there are missing USB ports.

**Comment by dhckdgjs** [comment]
step 1. Change USBPorts.kext(from Hackintool) to USBMap.kext(from USBMap script). - That means re-map all USB ports from the first using USBInjectall.kext. The attachement(USBMap.kext) in that thread is only for Z590 vision g M/B.
step 2. XhciLimitPort(in Quirks) uncheck and add 2 Kernel patches.

If you did 2 steps already, it will solve that issue.
I checked that fix works well with B460M, X299, Z490 chipsets.

If it won't work normally just notice me again.
I'll check tomorrow in my office :)

**Comment by ClassicOldSong** [comment]
I've followed the steps and still no luck.

The USB3.0 ports can work with USB2.0 speed, but not 3.0. If you check with IOJones you'll find all USB3.0 devices only have a speed of 0x2, which means USB HighSpeed but not SuperSpeed. I've checked with several USB3 devices, all behaves the same.

![image](https://user-images.githubusercontent.com/10512422/116299814-bbc1ab80-a7d0-11eb-83f5-8f06e2c04c7d.png)

![image](https://user-images.githubusercontent.com/10512422/116300006-f592b200-a7d0-11eb-9fc4-6d5bea7249a3.png)

**Comment by dhckdgjs** [comment]
That quick fix works normally in my system.
Using a newer version(1.1) of entire EFI, your USB ports work well probably.
<img width="848" alt="hackintool" src="https://user-images.githubusercontent.com/35429874/116491241-67075900-a8d4-11eb-887c-195cdfe2a537.png">
<img width="1030" alt="ioreg usb3 ss03" src="https://user-images.githubusercontent.com/35429874/116491774-9d91a380-a8d5-11eb-8bb9-98e650ba1918.png">

**Comment by dhckdgjs** [comment]
Sorry ClassicOldSong.
My colleague(he has same gear) told me 2 ports does not work properly.
I'll fix usb map for prime z390-a again ASAP :)

**Comment by ClassicOldSong** [comment]
No hurry, currently I'm on USB2.0 only mode, at least most things work and I got sleep fixed. Thanks for your testing!

Probably this could only be solved after new kernel source is released.

**Comment by dhckdgjs** [comment]
Please use updated EFI ver 1.2.
You can't use HS09, HS10 cause I set USB 15 port limit.
Other ports works well.
<img width="848" alt="스크린샷 2021-04-30 오전 9 38 58" src="https://user-images.githubusercontent.com/35429874/116662575-e5492580-a9d0-11eb-82a8-fe192a07093d.png">

**Comment by ClassicOldSong** [comment]
I followed your changes and edited my own USBPorts.kext and it works!

Though HS/SS09/10 are disabled now but I could change devices to other ports or adding a USB hub.

Thanks very much for the help!

**Comment by dhckdgjs** [comment]
Gratz! ;)
